import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "en" | "hi" | "te" | "ta";

const translations: Record<Lang, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    upload_bill: "Upload Bill",
    document_analysis: "Document Analysis",
    ask_the_bill: "Ask the Bill",
    bill_comparison: "Bill Comparison",
    token_efficiency: "Token Efficiency",
    knowledge_graph: "Knowledge Graph",
    compliance_checker: "Compliance Checker",
    amendment_tracker: "Amendment Tracker",
    bill_directory: "Bill Directory",
    settings: "Settings",
    upload: "Upload",
    search: "Search documents...",
    total_documents: "Total Documents",
    analyzed: "Analyzed",
    avg_compression: "Avg. Compression",
    total_tokens: "Total Tokens",
    your_documents: "Your Documents",
    no_documents: "No documents found",
    upload_first: "Upload your first document to get started",
    view: "View",
    delete: "Delete",
    export_pdf: "Export PDF",
    export_csv: "Export CSV",
    summary: "Summary",
    overview: "Overview",
    highlights: "Key Highlights",
    stakeholders: "Stakeholders",
    penalties: "Penalties",
    timeline: "Timeline",
    language_selection: "Language Selection",
    choose_language: "Choose your preferred language",
    theme: "Theme",
    light_mode: "Light Mode",
    dark_mode: "Dark Mode",
    sign_out: "Sign out",
    ask_question: "Ask a question...",
    select_document: "Select a document",
    general: "General (no document)",
    document_history: "Document History",
    version: "Version",
    no_versions: "No previous versions",
    customize_experience: "Customize your experience",
    // Bill Directory
    bill_directory_title: "Bill Directory",
    bill_directory_subtitle: "Browse Indian legislation by sector, state, and financial year",
    search_bills: "Search bills...",
    clear_filters: "Clear filters",
    bills_found: "bills found",
    bill_found: "bill found",
    financial_year_label: "Financial Year",
    summarize_bill: "Summarize Bill",
    re_summarize: "Re-summarize",
    summarizing: "Summarizing...",
    detailed_summary: "Detailed Summary",
    generating_summary: "Generating detailed summary...",
    view_source: "View Source",
    description: "Description",
    ministry: "Ministry",
    bill_type: "Bill Type",
    introduced_date: "Introduced Date",
    // Onboarding
    welcome: "Welcome",
    next: "Next",
    skip: "Skip",
    get_started: "Get Started",
    try_feature: "Try this feature",
    // PWA
    install_app: "Install App",
    install_description: "Install this app on your device for quick access",
    // General
    loading: "Loading...",
    error: "Error",
    success: "Success",
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    download: "Download",
    share: "Share",
    profile: "Profile",
    notifications: "Notifications",
    help: "Help",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    upload_bill: "बिल अपलोड करें",
    document_analysis: "दस्तावेज़ विश्लेषण",
    ask_the_bill: "बिल से पूछें",
    bill_comparison: "बिल तुलना",
    token_efficiency: "टोकन दक्षता",
    knowledge_graph: "ज्ञान ग्राफ",
    compliance_checker: "अनुपालन जाँचकर्ता",
    amendment_tracker: "संशोधन ट्रैकर",
    bill_directory: "विधेयक निर्देशिका",
    settings: "सेटिंग्स",
    upload: "अपलोड",
    search: "दस्तावेज़ खोजें...",
    total_documents: "कुल दस्तावेज़",
    analyzed: "विश्लेषित",
    avg_compression: "औसत संपीड़न",
    total_tokens: "कुल टोकन",
    your_documents: "आपके दस्तावेज़",
    no_documents: "कोई दस्तावेज़ नहीं मिला",
    upload_first: "शुरू करने के लिए अपना पहला दस्तावेज़ अपलोड करें",
    view: "देखें",
    delete: "हटाएं",
    export_pdf: "PDF निर्यात करें",
    export_csv: "CSV निर्यात करें",
    summary: "सारांश",
    overview: "अवलोकन",
    highlights: "मुख्य विशेषताएं",
    stakeholders: "हितधारक",
    penalties: "दंड",
    timeline: "समयरेखा",
    language_selection: "भाषा चयन",
    choose_language: "अपनी पसंदीदा भाषा चुनें",
    theme: "थीम",
    light_mode: "लाइट मोड",
    dark_mode: "डार्क मोड",
    sign_out: "साइन आउट",
    ask_question: "सवाल पूछें...",
    select_document: "दस्तावेज़ चुनें",
    general: "सामान्य (कोई दस्तावेज़ नहीं)",
    document_history: "दस्तावेज़ इतिहास",
    version: "संस्करण",
    no_versions: "कोई पिछला संस्करण नहीं",
    customize_experience: "अपना अनुभव अनुकूलित करें",
    // Bill Directory
    bill_directory_title: "विधेयक निर्देशिका",
    bill_directory_subtitle: "क्षेत्र, राज्य और वित्तीय वर्ष के अनुसार भारतीय विधान ब्राउज़ करें",
    search_bills: "विधेयक खोजें...",
    clear_filters: "फ़िल्टर साफ़ करें",
    bills_found: "विधेयक मिले",
    bill_found: "विधेयक मिला",
    financial_year_label: "वित्तीय वर्ष",
    summarize_bill: "विधेयक का सारांश",
    re_summarize: "पुनः सारांश",
    summarizing: "सारांश बना रहे हैं...",
    detailed_summary: "विस्तृत सारांश",
    generating_summary: "विस्तृत सारांश तैयार किया जा रहा है...",
    view_source: "स्रोत देखें",
    description: "विवरण",
    ministry: "मंत्रालय",
    bill_type: "विधेयक प्रकार",
    introduced_date: "प्रस्तुत तिथि",
    // Onboarding
    welcome: "स्वागत है",
    next: "अगला",
    skip: "छोड़ें",
    get_started: "शुरू करें",
    try_feature: "यह सुविधा आज़माएं",
    // PWA
    install_app: "ऐप इंस्टॉल करें",
    install_description: "त्वरित पहुंच के लिए इस ऐप को अपने डिवाइस पर इंस्टॉल करें",
    // General
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    success: "सफल",
    cancel: "रद्द करें",
    save: "सहेजें",
    close: "बंद करें",
    download: "डाउनलोड",
    share: "साझा करें",
    profile: "प्रोफ़ाइल",
    notifications: "सूचनाएं",
    help: "सहायता",
  },
  te: {
    dashboard: "డాష్‌బోర్డ్",
    upload_bill: "బిల్ అప్‌లోడ్",
    document_analysis: "పత్ర విశ్లేషణ",
    ask_the_bill: "బిల్‌ను అడగండి",
    bill_comparison: "బిల్ పోలిక",
    token_efficiency: "టోకెన్ సామర్థ్యం",
    knowledge_graph: "నాలెడ్జ్ గ్రాఫ్",
    compliance_checker: "సమ్మతి తనిఖీ",
    amendment_tracker: "సవరణ ట్రాకర్",
    bill_directory: "బిల్ డైరెక్టరీ",
    settings: "సెట్టింగ్‌లు",
    upload: "అప్‌లోడ్",
    search: "పత్రాలను వెతకండి...",
    total_documents: "మొత్తం పత్రాలు",
    analyzed: "విశ్లేషించబడింది",
    avg_compression: "సగటు కుదింపు",
    total_tokens: "మొత్తం టోకెన్‌లు",
    your_documents: "మీ పత్రాలు",
    no_documents: "పత్రాలు కనుగొనబడలేదు",
    upload_first: "ప్రారంభించడానికి మీ మొదటి పత్రాన్ని అప్‌లోడ్ చేయండి",
    view: "చూడండి",
    delete: "తొలగించు",
    export_pdf: "PDF ఎగుమతి",
    export_csv: "CSV ఎగుమతి",
    summary: "సారాంశం",
    overview: "అవలోకనం",
    highlights: "ముఖ్య విషయాలు",
    stakeholders: "వాటాదారులు",
    penalties: "జరిమానాలు",
    timeline: "సమయ రేఖ",
    language_selection: "భాష ఎంపిక",
    choose_language: "మీ ఇష్టమైన భాషను ఎంచుకోండి",
    theme: "థీమ్",
    light_mode: "లైట్ మోడ్",
    dark_mode: "డార్క్ మోడ్",
    sign_out: "సైన్ అవుట్",
    ask_question: "ప్రశ్న అడగండి...",
    select_document: "పత్రాన్ని ఎంచుకోండి",
    general: "సాధారణ (పత్రం లేదు)",
    document_history: "పత్ర చరిత్ర",
    version: "సంస్కరణ",
    no_versions: "మునుపటి సంస్కరణలు లేవు",
    customize_experience: "మీ అనుభవాన్ని అనుకూలీకరించండి",
    bill_directory_title: "బిల్ డైరెక్టరీ",
    bill_directory_subtitle: "రంగం, రాష్ట్రం మరియు ఆర్థిక సంవత్సరం ద్వారా భారతీయ చట్టాలను బ్రౌజ్ చేయండి",
    search_bills: "బిల్లులను వెతకండి...",
    clear_filters: "ఫిల్టర్లు తొలగించండి",
    bills_found: "బిల్లులు కనుగొనబడ్డాయి",
    bill_found: "బిల్లు కనుగొనబడింది",
    financial_year_label: "ఆర్థిక సంవత్సరం",
    summarize_bill: "బిల్లును సారాంశం చేయండి",
    re_summarize: "మళ్ళీ సారాంశం",
    summarizing: "సారాంశం చేస్తోంది...",
    detailed_summary: "వివరణాత్మక సారాంశం",
    generating_summary: "వివరణాత్మక సారాంశం తయారు చేస్తోంది...",
    view_source: "మూలాన్ని చూడండి",
    description: "వివరణ",
    ministry: "మంత్రిత్వ శాఖ",
    bill_type: "బిల్లు రకం",
    introduced_date: "ప్రవేశపెట్టిన తేదీ",
    welcome: "స్వాగతం",
    next: "తదుపరి",
    skip: "దాటవేయి",
    get_started: "ప్రారంభించండి",
    try_feature: "ఈ ఫీచర్ ప్రయత్నించండి",
    install_app: "యాప్ ఇన్‌స్టాల్ చేయండి",
    install_description: "త్వరిత యాక్సెస్ కోసం ఈ యాప్‌ను మీ పరికరంలో ఇన్‌స్టాల్ చేయండి",
    loading: "లోడ్ అవుతోంది...",
    error: "లోపం",
    success: "విజయం",
    cancel: "రద్దు",
    save: "సేవ్",
    close: "మూసివేయి",
    download: "డౌన్‌లోడ్",
    share: "షేర్",
    profile: "ప్రొఫైల్",
    notifications: "నోటిఫికేషన్లు",
    help: "సహాయం",
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    upload_bill: "மசோதா பதிவேற்றம்",
    document_analysis: "ஆவண பகுப்பாய்வு",
    ask_the_bill: "மசோதாவிடம் கேளுங்கள்",
    bill_comparison: "மசோதா ஒப்பீடு",
    token_efficiency: "டோக்கன் திறன்",
    knowledge_graph: "அறிவு வரைபடம்",
    compliance_checker: "இணக்கச் சரிபார்ப்பு",
    amendment_tracker: "திருத்தம் கண்காணிப்பான்",
    bill_directory: "மசோதா அடைவு",
    settings: "அமைப்புகள்",
    upload: "பதிவேற்றம்",
    search: "ஆவணங்களைத் தேடுங்கள்...",
    total_documents: "மொத்த ஆவணங்கள்",
    analyzed: "பகுப்பாய்வு செய்யப்பட்டது",
    avg_compression: "சராசரி சுருக்கம்",
    total_tokens: "மொத்த டோக்கன்கள்",
    your_documents: "உங்கள் ஆவணங்கள்",
    no_documents: "ஆவணங்கள் கிடைக்கவில்லை",
    upload_first: "தொடங்க உங்கள் முதல் ஆவணத்தைப் பதிவேற்றுங்கள்",
    view: "பார்",
    delete: "நீக்கு",
    export_pdf: "PDF ஏற்றுமதி",
    export_csv: "CSV ஏற்றுமதி",
    summary: "சுருக்கம்",
    overview: "கண்ணோட்டம்",
    highlights: "முக்கிய அம்சங்கள்",
    stakeholders: "பங்குதாரர்கள்",
    penalties: "அபராதங்கள்",
    timeline: "காலவரிசை",
    language_selection: "மொழி தேர்வு",
    choose_language: "உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    theme: "தீம்",
    light_mode: "லைட் மோட்",
    dark_mode: "டார்க் மோட்",
    sign_out: "வெளியேறு",
    ask_question: "கேள்வி கேளுங்கள்...",
    select_document: "ஆவணத்தைத் தேர்ந்தெடுக்கவும்",
    general: "பொது (ஆவணம் இல்லை)",
    document_history: "ஆவண வரலாறு",
    version: "பதிப்பு",
    no_versions: "முந்தைய பதிப்புகள் இல்லை",
    customize_experience: "உங்கள் அனுபவத்தை தனிப்பயனாக்குங்கள்",
    bill_directory_title: "மசோதா அடைவு",
    bill_directory_subtitle: "துறை, மாநிலம் மற்றும் நிதியாண்டு வாரியாக இந்திய சட்டங்களை உலாவுங்கள்",
    search_bills: "மசோதாக்களைத் தேடுங்கள்...",
    clear_filters: "வடிகட்டிகளை அழிக்கவும்",
    bills_found: "மசோதாக்கள் கிடைத்தன",
    bill_found: "மசோதா கிடைத்தது",
    financial_year_label: "நிதியாண்டு",
    summarize_bill: "மசோதாவை சுருக்கவும்",
    re_summarize: "மீண்டும் சுருக்கவும்",
    summarizing: "சுருக்குகிறது...",
    detailed_summary: "விரிவான சுருக்கம்",
    generating_summary: "விரிவான சுருக்கம் தயாரிக்கப்படுகிறது...",
    view_source: "மூலத்தைப் பார்க்கவும்",
    description: "விளக்கம்",
    ministry: "அமைச்சகம்",
    bill_type: "மசோதா வகை",
    introduced_date: "அறிமுகப்படுத்திய தேதி",
    welcome: "வரவேற்கிறோம்",
    next: "அடுத்து",
    skip: "தவிர்",
    get_started: "தொடங்குங்கள்",
    try_feature: "இந்த அம்சத்தை முயற்சிக்கவும்",
    install_app: "ஆப்பை நிறுவுங்கள்",
    install_description: "விரைவான அணுகலுக்கு இந்த ஆப்பை உங்கள் சாதனத்தில் நிறுவுங்கள்",
    loading: "ஏற்றுகிறது...",
    error: "பிழை",
    success: "வெற்றி",
    cancel: "ரத்துசெய்",
    save: "சேமி",
    close: "மூடு",
    download: "பதிவிறக்கு",
    share: "பகிர்",
    profile: "சுயவிவரம்",
    notifications: "அறிவிப்புகள்",
    help: "உதவி",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    return (localStorage.getItem("app-lang") as Lang) || "en";
  });

  const changeLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem("app-lang", l);
  };

  const t = (key: string) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
